---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - printf '---\n- hosts: localhost\n  remote_user: root\n  roles:\n    - .' >test.yml
  - printf 'localhost' >hosts.ini

script:
  # Basic role syntax check
  - ansible-playbook test.yml -i hosts.ini --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
