name: Ansible check archlinux:latest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible check with archlinux:latest
      uses: roles-ansible/check-ansible-archlinux-latest-action@master
      with:
        targets: "./"
